### ISSUE TITLE
anonymizer does not work on tinyint colums

### ISSUE THREAD

**Issue by ukirsten** [rosmo/mydumper-anon#7]
hello, what a great tool! :smile:

when i define the following yaml the actual value is not empty afterwards. based on my investigation it seems to be related with the tinyint column. i tried also various other syntax for 1 (wrapped as string, as regex pattern etc. pp.) but it seems to never match so value is not emptied

```
table_name:
     edit:
       - when: {default: 1}
         set: {value: ''}
```
